"""add expire time to urls

Revision ID: 13b88e2b7011
Revises: bb965407d943
Create Date: 2026-02-17 14:35:01.145637

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "13b88e2b7011"
down_revision: str | Sequence[str] | None = "bb965407d943"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("url", sa.Column("expire_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("url", "expire_at")
    # ### end Alembic commands ###
